# Generated by Django 3.1.7 on 2021-04-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shloka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveSmallIntegerField()),
                ('shloka_no', models.PositiveSmallIntegerField()),
                ('shloka', models.TextField()),
                ('word_meaning', models.TextField()),
                ('meaning', models.TextField()),
                ('explanation', models.TextField()),
                ('video_url', models.URLField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('chapter', 'shloka_no')},
            },
        ),
    ]
