# Generated by Django 3.1.7 on 2021-04-08 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shloka_feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shloka',
            name='quizIsActive',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveSmallIntegerField()),
                ('shloka_no', models.PositiveSmallIntegerField()),
                ('question', models.TextField()),
                ('optionA', models.TextField(verbose_name='Option A')),
                ('optionB', models.TextField(verbose_name='Option B')),
                ('optionC', models.TextField(verbose_name='Option C')),
                ('optionD', models.TextField(verbose_name='Option D')),
                ('answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], default='A', max_length=1)),
                ('point', models.PositiveSmallIntegerField(default=5)),
                ('shloka_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shloka_feed.shloka')),
            ],
        ),
    ]
