# Generated by Django 3.0.5 on 2020-04-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shloka_feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shloka',
            name='video_link',
        ),
        migrations.AddField(
            model_name='shloka',
            name='video_id',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
