# Generated by Django 3.1.6 on 2021-04-09 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shloka_feed', '0002_auto_20210408_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizmodel',
            old_name='shloka_id',
            new_name='shloka',
        ),
    ]
