# Generated by Django 3.0.5 on 2020-05-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shloka_feed', '0002_auto_20200429_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shloka',
            name='video_id',
            field=models.URLField(),
        ),
    ]
