# Generated by Django 3.0.5 on 2020-05-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shloka_feed', '0003_auto_20200503_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shloka',
            old_name='video_id',
            new_name='video_url',
        ),
    ]
