# Generated by Django 3.0.6 on 2020-05-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shloka_feed', '0004_auto_20200503_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shloka',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
